platform :ios, '8.0'
use_frameworks!

target 'YoutubeChannelFinder' do
	pod 'Alamofire', '~> 3.4'
	pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
	pod "youtube-ios-player-helper", "~> 0.1.6”
end

